//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgresadosU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egresados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egresados()
        {
            this.ActividadesEgresados = new HashSet<ActividadesEgresados>();
            this.OfertasEgresados = new HashSet<OfertasEgresados>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdPrograma { get; set; }
        public Nullable<System.DateTime> FechaEgreso { get; set; }
        public string TarjetaProfesional { get; set; }
    
        public virtual Programas Programas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadesEgresados> ActividadesEgresados { get; set; }
        public virtual Personas Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfertasEgresados> OfertasEgresados { get; set; }
    }
}
