//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgresadosU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstitucionalEntities : DbContext
    {
        public InstitucionalEntities()
            : base("name=InstitucionalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Instituciones> Instituciones { get; set; }
        public virtual DbSet<NivelesFormación> NivelesFormación { get; set; }
        public virtual DbSet<Programas> Programas { get; set; }
        public virtual DbSet<Sedes> Sedes { get; set; }
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<ActividadesEgresados> ActividadesEgresados { get; set; }
        public virtual DbSet<Convocatorias> Convocatorias { get; set; }
        public virtual DbSet<Egresados> Egresados { get; set; }
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<OfertasEgresados> OfertasEgresados { get; set; }
        public virtual DbSet<OfertasLaborales> OfertasLaborales { get; set; }
        public virtual DbSet<Soportes> Soportes { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<DivisionesPoliticas> DivisionesPoliticas { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Niveles> Niveles { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<TiposDocumentos> TiposDocumentos { get; set; }
    }
}
